
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author USER
 */
public class UMSGUI extends javax.swing.JFrame {

    /**
     * Creates new form UMSGUI
     */
    public UMSGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lusername = new javax.swing.JLabel();
        tusername = new javax.swing.JTextField();
        lpassword = new javax.swing.JLabel();
        tpassword = new javax.swing.JTextField();
        bsignin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lusernameup = new javax.swing.JLabel();
        lpasswordup = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        tuserup = new javax.swing.JTextField();
        tpassup = new javax.swing.JTextField();
        tnameup = new javax.swing.JTextField();
        bsingup = new javax.swing.JButton();
        lage = new javax.swing.JLabel();
        tageup = new javax.swing.JTextField();
        tcourse = new javax.swing.JTextField();
        lcourseup = new javax.swing.JLabel();
        BRESET = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("            UNIVERSITY MANAGEMENT SYSTEM");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lusername.setText("Username");

        tusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tusernameActionPerformed(evt);
            }
        });

        lpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lpassword.setText("Password");

        bsignin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bsignin.setText("SIGNIN");
        bsignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsigninActionPerformed(evt);
            }
        });

        lusernameup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lusernameup.setText("Username-");

        lpasswordup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lpasswordup.setText("Password-");

        lname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lname.setText("Name");
        lname.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        bsingup.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bsingup.setText("SIGNUP");
        bsingup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsingupActionPerformed(evt);
            }
        });

        lage.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lage.setText("AGE");

        tcourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lcourseup.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lcourseup.setText("course no");

        BRESET.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BRESET.setText("RESET");
        BRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRESETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lpassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lusername, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tusername)
                                        .addComponent(tpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1)
                                .addGap(42, 42, 42))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lusernameup, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(68, 68, 68)
                                                                .addComponent(tuserup, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lpasswordup, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(lcourseup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(lage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                .addGap(42, 42, 42)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(tcourse)
                                                                        .addComponent(tnameup, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(tpassup)
                                                                        .addComponent(tageup))))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(80, 80, 80)
                                                                .addComponent(bsingup, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(89, 89, 89)
                                                                .addComponent(BRESET)))))
                                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lusername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(lpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(tpassword)
                                                                .addGap(7, 7, 7))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(bsignin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lusernameup, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(tuserup)
                                                .addGap(5, 5, 5)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tpassup, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lpasswordup, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bsingup, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(tnameup, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lage, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tageup, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BRESET, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 12, Short.MAX_VALUE)
                                                .addComponent(tcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lcourseup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>

    private void tusernameActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void bsigninActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String uname,pw;
        uname=tusername.getText();
        pw=tpassword.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/oop", "root", "tharun"
            );
            String sql = "SELECT memberdetail.Username,memberdetail.Password  FROM memberdetail ";
            String Name = null;
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();

            String sql1 = "SELECT Username,course_no FROM coursetable ";
            PreparedStatement st1 = con.prepareStatement(sql1);
            ResultSet rs1 = st1.executeQuery();

            while(rs.next()){
                String x=rs.getString(2);
                Name = rs.getString(1);

                if(uname.equals(Name)&&pw.equals(x)) {
                    while (rs1.next()) {
                        String y = rs1.getString(1);
                        if (uname.equals(y)) {
                           int cn =rs1.getInt(2);
                            JFrame f;
                            f=new JFrame();
                            switch(cn){
                                case 1:
                                    JOptionPane.showMessageDialog(f,"Hello "+Name+" you have selected course:SENG 11111 - Introduction to Programming"); break;
                                case 2:
                                    JOptionPane.showMessageDialog(f,"Hello "+Name+" you have selected course:SENG 11112 - Fundamentals of Engineering"); break;
                                case 3:
                                    JOptionPane.showMessageDialog(f,"Hello "+Name+" you have selected course SENG 11113 - Data Structures and Algorithms"); break;
                            }

                        }
                    }
                }
            }

        }
        catch(Exception e){
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
        }
    }






    private void bsingupActionPerformed(java.awt.event.ActionEvent evt) {
        String uname=tuserup.getText();
        String name=tnameup.getText();
        String pwd=tpassup.getText();
        String a=tageup.getText(); int age=Integer.parseInt(a);
        String se=tcourse.getText();  int select=Integer.parseInt(se);
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/oop", "root", "tharun");

            Statement st = con.createStatement();
            PreparedStatement sts = con.prepareStatement("insert into memberdetail(Username,Name,Password,AGE)" +
                    "values(?,?,?,?)");
            sts.setString(1, uname);
            sts.setString(2, name);
            sts.setString(3, pwd);
            sts.setInt(4, age);
            sts.executeUpdate();

            PreparedStatement sts1 = con.prepareStatement("insert into coursetable(Username,Course_no)" +
                    "values(?,?)");
            sts1.setString(1,uname);
            sts1.setInt(2,select);
            sts1.executeUpdate();
            con.close();

            JFrame f;
            f=new JFrame();
            JOptionPane.showMessageDialog(f,"Hello " +
                    ""+name+"  " );

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void BRESETActionPerformed(java.awt.event.ActionEvent evt) {
        tpassword.setText(null);tusername.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UMSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UMSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UMSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UMSGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UMSGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton BRESET;
    private javax.swing.JButton bsignin;
    private javax.swing.JButton bsingup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lage;
    private javax.swing.JLabel lcourseup;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel lpassword;
    private javax.swing.JLabel lpasswordup;
    private javax.swing.JLabel lusername;
    private javax.swing.JLabel lusernameup;
    private javax.swing.JTextField tageup;
    private javax.swing.JTextField tcourse;
    private javax.swing.JTextField tnameup;
    private javax.swing.JTextField tpassup;
    private javax.swing.JTextField tpassword;
    private javax.swing.JTextField tusername;
    private javax.swing.JTextField tuserup;
    // End of variables declaration
}
